export const PATH = {
  books: 'books',
  authors: 'authors',
  news: 'news',
  users: 'users',
  register: 'register',
  login: 'login',
  account: 'account',
  cart: 'cart',
  searchOptions: 'search_opts',
  verify: 'verify',
  passwordReset: 'password-reset',
  checkout: 'checkout',
  orders: 'orders',
}
