export { Layout } from './Layout/Layout'
export { Home } from './Home/Home'
export { Products } from './Products/Products'
export { Product } from './Product/Product'
export { Registration } from './Registration/Registration'
export { Login } from './Login/Login'
export { NotFound } from './NotFound/NotFound'
