const P = {
  books: 'books',
  authors: 'authors',
  news: 'news',
  searchOptions: 'search_opts',
  users: 'users',
  payments: 'payments',
  cms: 'cms',
  orders: 'orders',
  logs: 'logs',
} as const

export const PATH = {
  books: P.books,
  authors: P.authors,
  news: P.news,
  searchOptions: P.searchOptions,
  payments: P.payments,
  users: {
    register: `${P.users}/register`,
    login: `${P.users}/login`,
    logout: `${P.users}/logout`,
    verification: `${P.users}/verification`,
    passwordResetRequest: `${P.users}/password-reset-request`,
    passwordResetToken: `${P.users}/password-reset-token`,
    passwordResetSubmit: `${P.users}/password-reset-submit`,
    profile: `${P.users}/profile`,
    refresh: `${P.users}/refresh`,
    avatar: `${P.users}/avatar`,
    country: `${P.users}/country`,
    countryCodes: `${P.users}/country-codes`,
  },
  cms: {
    orders: `${P.cms}/${P.orders}`,
    users: `${P.cms}/${P.users}`,
    books: `${P.cms}/${P.books}`,
    authors: `${P.cms}/${P.authors}`,
    productImage: `${P.cms}/product-image`,
  },
  logs: P.logs,
} as const
