export type { IBook } from './IBook'
export type { IAuthor } from './IAuthor'
export type { IBookState } from './IState'
export type { IAuthorState } from './IState'
export type { ICardProps } from './ICardProps'
export type { IPriceProps } from './IPriceProps'
