export type { ICard } from './ICard'
export type { IBook } from './IBook'
export type { IAuthor } from './IAuthor'
export type { IBookState } from './IState'
export type { IAuthorState } from './IState'
